---
# tasks file for roles/prometheus
- name: Create prometheus user
  user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
- name: Copy prometheus binary
  copy:
    remote_src: yes
    src: /opt/prometheus-2.52.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'
- name: Copy promtool binary
  copy:
    remote_src: yes
    src: /opt/prometheus-2.52.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    mode: '0755'
- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Copy config file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus

      [Install]
      WantedBy=multi-user.target
- name: Copy Prometheus alert rules
  template:
    src: alert.rules.yml.j2
    dest: /etc/prometheus/alert.rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: 
    - daemon-reload prometheus
    - restart prometheus

- name: Start and enable prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes
