---
# tasks file for roles/common
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name: [curl, wget, unzip, ufw, gnupg2, software-properties-common]
    state: present

- name: Ensure CA certificates and Python dependencies
  apt:
    name:
      - ca-certificates
      - python3-pip
      - python3-urllib3
      - python3-openssl
    state: present
